void serveWelcome();
void serveFlashOn();
void serveFlashOff();
void serveImg();
void serveSpace();
void serveWipe();
void serveDelete();
void serveImgCount();
void initWifi();
void initServer();
void ledTask(void *params);
void sendEvent(LED_Event evt);